name = "she-lab-spot-the-bot"
main = "worker.js"
compatibility_date = "2024-07-01"

[[d1_databases]]
binding = "DB"
database_name = "spot-the-bot"
database_id = "91f32fa1-3b39-4d47-9cca-14e7b48063bc"
